USE [ZSBD_Ksiegarnia]
GO

/****** Object:  Table [dbo].[Jezyki]    Script Date: 05.06.2025 20:59:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Jezyki](
	[j_id] [int] IDENTITY(1,1) NOT NULL,
	[j_nazwa] [nvarchar](100) NOT NULL,
	[j_kod] [varchar](5) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[j_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


