USE [ZSBD_Ksiegarnia]
GO

/****** Object:  Table [dbo].[Seria]    Script Date: 05.06.2025 21:04:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Seria](
	[ser_id] [int] IDENTITY(1,1) NOT NULL,
	[ser_nazwa] [varchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[ser_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


